@echo off
echo Turning on compiler...
echo Compiling...
gcc bazowa.cpp dziedziczace.cpp game_screen.cpp mainmenu.cpp render_api.cpp SFMLFactory.cpp SFMLFactory.cpp wybor_typu_gry.cpp zapis_save_yes_no.cpp -o game.out
echo Completed!